### ISSUE TITLE
Broken link reference for blendshape

### ISSUE THREAD

**Issue by unsolublesugar** [HakuyaLabs/warudo-docs#19]
Hi, @TigerHix 
The URL provided as a reference link for blendshape on the [3D VTubing Primer page](https://docs.warudo.app/jp/docs/tutorials/3d-primer) seems to be broken.

> Reference: https://developpaper.com/unity-realizes-facial-expression-transition-and-switching-animation-tutorial-through-blendshape/

I don't know what the original site is, but I think it should be fixed. 
Can you provide an appropriate similar reference site?

**Comment by TigerHix** [comment]
It seems like the original site is down. I can't seem to find another source for the GIFs though, which is really unfortunate.

For now I have simply removed the links & retained the credit to the original website. Thanks for reporting!

**Comment by unsolublesugar** [comment]
Thanks for your prompt response!
Then, I'll correct the Japanese translation in the same way.
