### ISSUE TITLE
Japanese search problems

### ISSUE THREAD

**Issue by unsolublesugar** [HakuyaLabs/warudo-docs#26]
## Summary
Can't search for Hiragana and katakana keywords in Japanese.

![2024-07-09_13h05_47](https://github.com/HakuyaLabs/warudo-docs/assets/8685879/1cda453e-03ff-4727-bf83-42ed31cfb443)

If a keyword contains Kanji characters or English, it will appear in the search results for that keyword only.

![2024-07-09_12h38_05](https://github.com/HakuyaLabs/warudo-docs/assets/8685879/484fea42-e207-4e49-9c16-4256311dff62)

![2024-07-09_12h38_48](https://github.com/HakuyaLabs/warudo-docs/assets/8685879/2004e082-63c4-422f-bf3a-9bad25cf54d4)

## Reference Information

[cmfcmf/docusaurus-search-local](https://github.com/cmfcmf/docusaurus-search-local) , which is a fork of [easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) , has the following description in `tokenizerSeparator`, which may need to be addressed separately.
```js
  // lunr.js-specific settings
  lunr: {
    // When indexing your documents, their content is split into "tokens".
    // Text entered into the search box is also tokenized.
    // This setting configures the separator used to determine where to split the text into tokens.
    // By default, it splits the text at whitespace and dashes.
    //
    // Note: Does not work for "ja" and "th" languages, since these use a different tokenizer.
    tokenizerSeparator: /[\s\-]+/,
    // https://lunrjs.com/guides/customising.html#similarity-tuning
    //
    // This parameter controls the importance given to the length of a document and its fields. This
    // value must be between 0 and 1, and by default it has a value of 0.75. Reducing this value
    // reduces the effect of different length documents on a term’s importance to that document.
```
> https://github.com/cmfcmf/docusaurus-search-local?tab=readme-ov-file#usage

```js
  tokenizerSeparator: /[\s\-\u{3000}-\u{301C}\u{3041}-\u{3093}\u{309B}-\u{309E}]+/gu
```
> https://qiita.com/y_catch/items/46b7eb7d618d95fbc9c3

The currently employed easyops-cn plugin is missing the corresponding option.
Without seeing the details in action, it's hard to know how to respond.

**Comment by unsolublesugar** [comment]
Probably the same problem as this one (unresolved)

https://github.com/easyops-cn/docusaurus-search-local/issues/338

**Comment by TigerHix** [comment]
Thanks for the report! @Nekotora Maybe we can take a look into https://www.meilisearch.com/ mentioned as an alternative in the other issue?

**Comment by Nekotora** [comment]
Thanks for the report too. 🫡
The current local search plugin seems lack support for languages other than Chinese and English.
And with the document content continues to grow, the local index files are also becoming larger. (about 2MB per language now :x )

It might be time to consider finding a search backend.
I will take a closer look at Meilisearch and other solutions,
Sorry for the late reply, I've been a little busy recently. I will deal with that soon.

**Comment by unsolublesugar** [comment]
@Nekotora Thanks for taking the time to take a look!
If you ever need to check the Japanese environment to make sure it works, please give me a shout. ;)

**Comment by Nekotora** [comment]
Sorry for taking such a long time to fix it.🙇
The multi-language search results should be very smooth now.

I initially tried to fix local search with lunr.js or set up a self-hosted crawler,
but soon open-source free application at https://docsearch.algolia.com/ just approved, so we use Algolia for now.

If you have any questions, just let me know!

**Comment by unsolublesugar** [comment]
@Nekotora  Thanks for fixing this problem!
I checked at hand and everything works fine! :laughing:

![2024-07-19_10h19_29](https://github.com/user-attachments/assets/ecb08ce9-e0f6-4354-b3f8-7ffa2a6bd4e0)
![2024-07-19_10h21_53](https://github.com/user-attachments/assets/cdf6bee6-3066-47de-9865-70c3ac1dc224)
![2024-07-19_10h21_30](https://github.com/user-attachments/assets/f1c1b7f6-8d32-42d0-80f9-317747bb1c50)
